FROM mcr.microsoft.com/playwright:v1.39.0-jammy

RUN mkdir /test
WORKDIR /test

COPY package.json /test/
COPY package-lock.json /test/
COPY .storybook /test/.storybook
RUN npm ci

# Create entrypoint that accepts additional arguments
ENTRYPOINT ["npm", "run", "storybook:test", "--", "--url", "http://storybook:6006/", "--no-index-json"]
CMD []

