import { PlotData } from "../src/index";

/**
 * This is example data based on the Well Completions data in `well-completions.json`-file found in the `example-data`-folder.
 *
 * Some data has been removed to make the example data smaller. Mainly it's less time steps and less wells, but the data
 * is to show how the plot occurs with given PlotData data structure.
 */
export const sortedCompletionDates: string[] = [
    "2000-02-01",
    "2000-06-01",
    "2000-10-01",
];
export const firstPlotData: PlotData = {
    stratigraphy: [
        {
            name: "zone1.1",
            color: "#808080",
        },
        {
            name: "zone1.2",
            color: "#FF0000",
        },
        {
            name: "zone1.3",
            color: "#800000",
        },
        {
            name: "zone2.1",
            color: "#FFFF00",
        },
        {
            name: "zone2.2",
            color: "#808000",
        },
        {
            name: "zone2.3",
            color: "#00FF00",
        },
        {
            name: "zone3.1",
            color: "#008000",
        },
        {
            name: "zone3.2",
            color: "#00FFFF",
        },
        {
            name: "zone3.3",
            color: "#008080",
        },
        {
            name: "zone4.1",
            color: "#0000FF",
        },
        {
            name: "zone4.2",
            color: "#000080",
        },
        {
            name: "zone4.3",
            color: "#FF00FF",
        },
        {
            name: "zone4.4",
            color: "#800080",
        },
        {
            name: "zone4.5",
            color: "#C0C0C0",
        },
    ],
    wells: [
        {
            name: "PP_1",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 4,
                    open: 1,
                    shut: 0,
                    khMean: 1297.885520625,
                    khMin: 319.263714,
                    khMax: 2020.03044,
                },
                {
                    zoneIndex: 5,
                    open: 1,
                    shut: 0,
                    khMean: 5566.9085537500005,
                    khMin: 1425.47896,
                    khMax: 11862.0278,
                },
                {
                    zoneIndex: 6,
                    open: 1,
                    shut: 0,
                    khMean: 6939.8011750000005,
                    khMin: 3810.31034,
                    khMax: 13687.4375,
                },
                {
                    zoneIndex: 7,
                    open: 1,
                    shut: 0,
                    khMean: 9108.8909675,
                    khMin: 2322.1114,
                    khMax: 18026.9014,
                },
                {
                    zoneIndex: 8,
                    open: 1,
                    shut: 0,
                    khMean: 9014.676917499999,
                    khMin: 2374.64861,
                    khMax: 12787.8859,
                },
                {
                    zoneIndex: 9,
                    open: 1,
                    shut: 0,
                    khMean: 11183.50554875,
                    khMin: 5064.223779999998,
                    khMax: 17483.6525,
                },
                {
                    zoneIndex: 10,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Producer",
                region: "Region 1",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "OP_2",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 6,
                    open: 1,
                    shut: 0,
                    khMean: 7598.64078875,
                    khMin: 3437.2791799999995,
                    khMax: 14113.7892,
                },
                {
                    zoneIndex: 7,
                    open: 1,
                    shut: 0,
                    khMean: 11423.95092,
                    khMin: 5258.6867,
                    khMax: 17497.0243,
                },
                {
                    zoneIndex: 8,
                    open: 1,
                    shut: 0,
                    khMean: 10460.28144875,
                    khMin: 5421.12302,
                    khMax: 15721.4976,
                },
                {
                    zoneIndex: 9,
                    open: 1,
                    shut: 0,
                    khMean: 3809.3387337500003,
                    khMin: 2231.23747,
                    khMax: 5662.93419,
                },
                {
                    zoneIndex: 10,
                    open: 1,
                    shut: 0,
                    khMean: 15.149603771249998,
                    khMin: 8.46788526,
                    khMax: 39.9376641,
                },
                {
                    zoneIndex: 11,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Injector",
                region: "Region 4",
                "user defined category": "my group 1",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "OP_3",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 8,
                    open: 1,
                    shut: 0,
                    khMean: 2520.3137368749994,
                    khMin: 147.068421,
                    khMax: 9030.14994,
                },
                {
                    zoneIndex: 9,
                    open: 1,
                    shut: 0,
                    khMean: 4773.51814625,
                    khMin: 2794.09724,
                    khMax: 8241.87593,
                },
                {
                    zoneIndex: 10,
                    open: 1,
                    shut: 0,
                    khMean: 10122.645607499999,
                    khMin: 3013.539,
                    khMax: 17088.9797,
                },
                {
                    zoneIndex: 11,
                    open: 1,
                    shut: 0,
                    khMean: 9451.1859075,
                    khMin: 5410.000810000001,
                    khMax: 19663.403,
                },
                {
                    zoneIndex: 12,
                    open: 1,
                    shut: 0,
                    khMean: 11903.580101250001,
                    khMin: 3418.7660100000007,
                    khMax: 20178.9664,
                },
                {
                    zoneIndex: 13,
                    open: 1,
                    shut: 0,
                    khMean: 13180.41943125,
                    khMin: 8451.82401,
                    khMax: 20863.3268,
                },
            ],
            attributes: {
                type: "Injector",
                region: "Region 1",
                "user defined category": "my group 2",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "RWI_2",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Injector",
                region: "Region 1",
                "user defined category": "my group 1",
            },
            earliestCompDateIndex: 1,
        },
        {
            name: "WI_1",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 1,
                    open: 1,
                    shut: 0,
                    khMean: 1231.3151895,
                    khMin: 331.081127,
                    khMax: 1672.92916,
                },
                {
                    zoneIndex: 2,
                    open: 1,
                    shut: 0,
                    khMean: 2713.00017425,
                    khMin: 822.713974,
                    khMax: 4422.29676,
                },
                {
                    zoneIndex: 3,
                    open: 1,
                    shut: 0,
                    khMean: 506.8437355,
                    khMin: 130.791149,
                    khMax: 1026.68084,
                },
                {
                    zoneIndex: 4,
                    open: 1,
                    shut: 0,
                    khMean: 781.5949868750001,
                    khMin: 385.392444,
                    khMax: 1506.72756,
                },
                {
                    zoneIndex: 5,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Producer",
                region: "Region 2",
                "user defined category": "my group 2",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "WI_2",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Producer",
                region: "Region 2",
                "user defined category": "my group 1",
            },
            earliestCompDateIndex: 1,
        },
    ],
    units: {
        kh: {
            unit: "mDm",
            decimalPlaces: 2,
        },
    },
};

export const secondPlotData: PlotData = {
    stratigraphy: [
        {
            name: "zone1.1",
            color: "#808080",
        },
        {
            name: "zone1.2",
            color: "#FF0000",
        },
        {
            name: "zone1.3",
            color: "#800000",
        },
        {
            name: "zone2.1",
            color: "#FFFF00",
        },
        {
            name: "zone2.2",
            color: "#808000",
        },
        {
            name: "zone2.3",
            color: "#00FF00",
        },
        {
            name: "zone3.1",
            color: "#008000",
        },
        {
            name: "zone3.2",
            color: "#00FFFF",
        },
        {
            name: "zone3.3",
            color: "#008080",
        },
        {
            name: "zone4.1",
            color: "#0000FF",
        },
        {
            name: "zone4.2",
            color: "#000080",
        },
        {
            name: "zone4.3",
            color: "#FF00FF",
        },
        {
            name: "zone4.4",
            color: "#800080",
        },
        {
            name: "zone4.5",
            color: "#C0C0C0",
        },
    ],
    wells: [
        {
            name: "OP_1",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 4,
                    open: 1,
                    shut: 0,
                    khMean: 1297.885520625,
                    khMin: 319.263714,
                    khMax: 2020.03044,
                },
                {
                    zoneIndex: 5,
                    open: 1,
                    shut: 0,
                    khMean: 5566.9085537500005,
                    khMin: 1425.47896,
                    khMax: 11862.0278,
                },
                {
                    zoneIndex: 6,
                    open: 1,
                    shut: 0,
                    khMean: 6939.8011750000005,
                    khMin: 3810.31034,
                    khMax: 13687.4375,
                },
                {
                    zoneIndex: 7,
                    open: 1,
                    shut: 0,
                    khMean: 9108.8909675,
                    khMin: 2322.1114,
                    khMax: 18026.9014,
                },
                {
                    zoneIndex: 8,
                    open: 1,
                    shut: 0,
                    khMean: 9014.676917499999,
                    khMin: 2374.64861,
                    khMax: 12787.8859,
                },
                {
                    zoneIndex: 9,
                    open: 1,
                    shut: 0,
                    khMean: 11183.50554875,
                    khMin: 5064.223779999998,
                    khMax: 17483.6525,
                },
                {
                    zoneIndex: 10,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Producer",
                region: "Region 1",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "OP_2",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 6,
                    open: 1,
                    shut: 0,
                    khMean: 7598.64078875,
                    khMin: 3437.2791799999995,
                    khMax: 14113.7892,
                },
                {
                    zoneIndex: 7,
                    open: 1,
                    shut: 0,
                    khMean: 11423.95092,
                    khMin: 5258.6867,
                    khMax: 17497.0243,
                },
                {
                    zoneIndex: 8,
                    open: 1,
                    shut: 0,
                    khMean: 10460.28144875,
                    khMin: 5421.12302,
                    khMax: 15721.4976,
                },
                {
                    zoneIndex: 9,
                    open: 1,
                    shut: 0,
                    khMean: 3809.3387337500003,
                    khMin: 2231.23747,
                    khMax: 5662.93419,
                },
                {
                    zoneIndex: 10,
                    open: 1,
                    shut: 0,
                    khMean: 15.149603771249998,
                    khMin: 8.46788526,
                    khMax: 39.9376641,
                },
                {
                    zoneIndex: 11,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Injector",
                region: "Region 4",
                "user defined category": "my group 1",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "OP_3",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 8,
                    open: 1,
                    shut: 0,
                    khMean: 2520.3137368749994,
                    khMin: 147.068421,
                    khMax: 9030.14994,
                },
                {
                    zoneIndex: 9,
                    open: 1,
                    shut: 0,
                    khMean: 4773.51814625,
                    khMin: 2794.09724,
                    khMax: 8241.87593,
                },
                {
                    zoneIndex: 10,
                    open: 1,
                    shut: 0,
                    khMean: 10122.645607499999,
                    khMin: 3013.539,
                    khMax: 17088.9797,
                },
                {
                    zoneIndex: 11,
                    open: 1,
                    shut: 0,
                    khMean: 9451.1859075,
                    khMin: 5410.000810000001,
                    khMax: 19663.403,
                },
                {
                    zoneIndex: 12,
                    open: 1,
                    shut: 0,
                    khMean: 11903.580101250001,
                    khMin: 3418.7660100000007,
                    khMax: 20178.9664,
                },
                {
                    zoneIndex: 13,
                    open: 1,
                    shut: 0,
                    khMean: 13180.41943125,
                    khMin: 8451.82401,
                    khMax: 20863.3268,
                },
            ],
            attributes: {
                type: "Injector",
                region: "Region 1",
                "user defined category": "my group 2",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "RWI_2",
            completions: [
                {
                    zoneIndex: 0,
                    open: 1,
                    shut: 0,
                    khMean: 966.9586572375,
                    khMin: 31.3075587,
                    khMax: 7692.28216,
                },
                {
                    zoneIndex: 1,
                    open: 1,
                    shut: 0,
                    khMean: 737.2361547500001,
                    khMin: 202.004725,
                    khMax: 4206.10736,
                },
                {
                    zoneIndex: 2,
                    open: 1,
                    shut: 0,
                    khMean: 231.151925,
                    khMin: 162.731573,
                    khMax: 263.711042,
                },
                {
                    zoneIndex: 3,
                    open: 1,
                    shut: 0,
                    khMean: 365.64561212499996,
                    khMin: 124.641662,
                    khMax: 1487.41025,
                },
                {
                    zoneIndex: 4,
                    open: 1,
                    shut: 0,
                    khMean: 1388.1157115,
                    khMin: 50.1634623,
                    khMax: 9609.91712,
                },
                {
                    zoneIndex: 5,
                    open: 1,
                    shut: 0,
                    khMean: 1311.91390607875,
                    khMin: 6.82584143,
                    khMax: 9238.60455,
                },
                {
                    zoneIndex: 6,
                    open: 1,
                    shut: 0,
                    khMean: 1443.4808,
                    khMin: 602.083604,
                    khMax: 2368.27406,
                },
                {
                    zoneIndex: 7,
                    open: 1,
                    shut: 0,
                    khMean: 4143.0275075,
                    khMin: 2136.6255,
                    khMax: 6521.29951,
                },
                {
                    zoneIndex: 8,
                    open: 1,
                    shut: 0,
                    khMean: 2780.9278937500003,
                    khMin: 1156.0911,
                    khMax: 6190.71447,
                },
                {
                    zoneIndex: 9,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 10,
                    open: 1,
                    shut: 0,
                    khMean: 36.873345055,
                    khMin: 4.80656063,
                    khMax: 242.525623,
                },
                {
                    zoneIndex: 11,
                    open: 1,
                    shut: 0,
                    khMean: 153.26354434125003,
                    khMin: 3.88889919,
                    khMax: 687.152499,
                },
                {
                    zoneIndex: 12,
                    open: 1,
                    shut: 0,
                    khMean: 687.2094793074999,
                    khMin: 3.74611457,
                    khMax: 2881.7809,
                },
                {
                    zoneIndex: 13,
                    open: 1,
                    shut: 0,
                    khMean: 558.90722366125,
                    khMin: 2.9843909,
                    khMax: 2151.45851,
                },
            ],
            attributes: {
                type: "Injector",
                region: "Region 1",
                "user defined category": "my group 1",
            },
            earliestCompDateIndex: 1,
        },
        {
            name: "WI_1",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 1,
                    open: 1,
                    shut: 0,
                    khMean: 1231.3151895,
                    khMin: 331.081127,
                    khMax: 1672.92916,
                },
                {
                    zoneIndex: 2,
                    open: 1,
                    shut: 0,
                    khMean: 2713.00017425,
                    khMin: 822.713974,
                    khMax: 4422.29676,
                },
                {
                    zoneIndex: 3,
                    open: 1,
                    shut: 0,
                    khMean: 506.8437355,
                    khMin: 130.791149,
                    khMax: 1026.68084,
                },
                {
                    zoneIndex: 4,
                    open: 1,
                    shut: 0,
                    khMean: 781.5949868750001,
                    khMin: 385.392444,
                    khMax: 1506.72756,
                },
                {
                    zoneIndex: 5,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Producer",
                region: "Region 2",
                "user defined category": "my group 2",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "WI_2",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 9,
                    open: 1,
                    shut: 0,
                    khMean: 2.01463155625,
                    khMin: 0.68573069,
                    khMax: 6.83388483,
                },
                {
                    zoneIndex: 10,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Producer",
                region: "Region 2",
                "user defined category": "my group 1",
            },
            earliestCompDateIndex: 1,
        },
    ],
    units: {
        kh: {
            unit: "mDm",
            decimalPlaces: 2,
        },
    },
};

export const thirdPlotData: PlotData = {
    stratigraphy: [
        {
            name: "zone1.1",
            color: "#808080",
        },
        {
            name: "zone1.2",
            color: "#FF0000",
        },
        {
            name: "zone1.3",
            color: "#800000",
        },
        {
            name: "zone2.1",
            color: "#FFFF00",
        },
        {
            name: "zone2.2",
            color: "#808000",
        },
        {
            name: "zone2.3",
            color: "#00FF00",
        },
        {
            name: "zone3.1",
            color: "#008000",
        },
        {
            name: "zone3.2",
            color: "#00FFFF",
        },
        {
            name: "zone3.3",
            color: "#008080",
        },
        {
            name: "zone4.1",
            color: "#0000FF",
        },
        {
            name: "zone4.2",
            color: "#000080",
        },
        {
            name: "zone4.3",
            color: "#FF00FF",
        },
        {
            name: "zone4.4",
            color: "#800080",
        },
        {
            name: "zone4.5",
            color: "#C0C0C0",
        },
    ],
    wells: [
        {
            name: "OP_1",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 4,
                    open: 0.125,
                    shut: 0.875,
                    khMean: 1297.885520625,
                    khMin: 319.263714,
                    khMax: 2020.03044,
                },
                {
                    zoneIndex: 5,
                    open: 0.125,
                    shut: 0.875,
                    khMean: 5566.9085537500005,
                    khMin: 1425.47896,
                    khMax: 11862.0278,
                },
                {
                    zoneIndex: 6,
                    open: 0.125,
                    shut: 0.875,
                    khMean: 6939.8011750000005,
                    khMin: 3810.31034,
                    khMax: 13687.4375,
                },
                {
                    zoneIndex: 7,
                    open: 0.125,
                    shut: 0.875,
                    khMean: 9108.8909675,
                    khMin: 2322.1114,
                    khMax: 18026.9014,
                },
                {
                    zoneIndex: 8,
                    open: 0.125,
                    shut: 0.875,
                    khMean: 9014.676917499999,
                    khMin: 2374.64861,
                    khMax: 12787.8859,
                },
                {
                    zoneIndex: 9,
                    open: 0.125,
                    shut: 0.875,
                    khMean: 11183.50554875,
                    khMin: 5064.223779999998,
                    khMax: 17483.6525,
                },
                {
                    zoneIndex: 10,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Producer",
                region: "Region 1",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "OP_2",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 6,
                    open: 0.25,
                    shut: 0.75,
                    khMean: 7598.64078875,
                    khMin: 3437.2791799999995,
                    khMax: 14113.7892,
                },
                {
                    zoneIndex: 7,
                    open: 0.25,
                    shut: 0.75,
                    khMean: 11423.95092,
                    khMin: 5258.6867,
                    khMax: 17497.0243,
                },
                {
                    zoneIndex: 8,
                    open: 0.25,
                    shut: 0.75,
                    khMean: 10460.28144875,
                    khMin: 5421.12302,
                    khMax: 15721.4976,
                },
                {
                    zoneIndex: 9,
                    open: 0.25,
                    shut: 0.75,
                    khMean: 3809.3387337500003,
                    khMin: 2231.23747,
                    khMax: 5662.93419,
                },
                {
                    zoneIndex: 10,
                    open: 0.25,
                    shut: 0.75,
                    khMean: 15.149603771249998,
                    khMin: 8.46788526,
                    khMax: 39.9376641,
                },
                {
                    zoneIndex: 11,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Injector",
                region: "Region 4",
                "user defined category": "my group 1",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "OP_3",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 8,
                    open: 0.75,
                    shut: 0.25,
                    khMean: 2520.3137368749994,
                    khMin: 147.068421,
                    khMax: 9030.14994,
                },
                {
                    zoneIndex: 9,
                    open: 0.75,
                    shut: 0.25,
                    khMean: 4773.51814625,
                    khMin: 2794.09724,
                    khMax: 8241.87593,
                },
                {
                    zoneIndex: 10,
                    open: 0.75,
                    shut: 0.25,
                    khMean: 10122.645607499999,
                    khMin: 3013.539,
                    khMax: 17088.9797,
                },
                {
                    zoneIndex: 11,
                    open: 0.75,
                    shut: 0.25,
                    khMean: 9451.1859075,
                    khMin: 5410.000810000001,
                    khMax: 19663.403,
                },
                {
                    zoneIndex: 12,
                    open: 0.75,
                    shut: 0.25,
                    khMean: 11903.580101250001,
                    khMin: 3418.7660100000007,
                    khMax: 20178.9664,
                },
                {
                    zoneIndex: 13,
                    open: 0.75,
                    shut: 0.25,
                    khMean: 13180.41943125,
                    khMin: 8451.82401,
                    khMax: 20863.3268,
                },
            ],
            attributes: {
                type: "Injector",
                region: "Region 1",
                "user defined category": "my group 2",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "RWI_2",
            completions: [
                {
                    zoneIndex: 0,
                    open: 1,
                    shut: 0,
                    khMean: 966.9586572375,
                    khMin: 31.3075587,
                    khMax: 7692.28216,
                },
                {
                    zoneIndex: 1,
                    open: 1,
                    shut: 0,
                    khMean: 737.2361547500001,
                    khMin: 202.004725,
                    khMax: 4206.10736,
                },
                {
                    zoneIndex: 2,
                    open: 1,
                    shut: 0,
                    khMean: 231.151925,
                    khMin: 162.731573,
                    khMax: 263.711042,
                },
                {
                    zoneIndex: 3,
                    open: 1,
                    shut: 0,
                    khMean: 365.64561212499996,
                    khMin: 124.641662,
                    khMax: 1487.41025,
                },
                {
                    zoneIndex: 4,
                    open: 1,
                    shut: 0,
                    khMean: 1388.1157115,
                    khMin: 50.1634623,
                    khMax: 9609.91712,
                },
                {
                    zoneIndex: 5,
                    open: 1,
                    shut: 0,
                    khMean: 1311.91390607875,
                    khMin: 6.82584143,
                    khMax: 9238.60455,
                },
                {
                    zoneIndex: 6,
                    open: 1,
                    shut: 0,
                    khMean: 1443.4808,
                    khMin: 602.083604,
                    khMax: 2368.27406,
                },
                {
                    zoneIndex: 7,
                    open: 1,
                    shut: 0,
                    khMean: 4143.0275075,
                    khMin: 2136.6255,
                    khMax: 6521.29951,
                },
                {
                    zoneIndex: 8,
                    open: 1,
                    shut: 0,
                    khMean: 2780.9278937500003,
                    khMin: 1156.0911,
                    khMax: 6190.71447,
                },
                {
                    zoneIndex: 9,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 10,
                    open: 1,
                    shut: 0,
                    khMean: 36.873345055,
                    khMin: 4.80656063,
                    khMax: 242.525623,
                },
                {
                    zoneIndex: 11,
                    open: 1,
                    shut: 0,
                    khMean: 153.26354434125003,
                    khMin: 3.88889919,
                    khMax: 687.152499,
                },
                {
                    zoneIndex: 12,
                    open: 1,
                    shut: 0,
                    khMean: 687.2094793074999,
                    khMin: 3.74611457,
                    khMax: 2881.7809,
                },
                {
                    zoneIndex: 13,
                    open: 1,
                    shut: 0,
                    khMean: 558.90722366125,
                    khMin: 2.9843909,
                    khMax: 2151.45851,
                },
            ],
            attributes: {
                type: "Injector",
                region: "Region 1",
                "user defined category": "my group 1",
            },
            earliestCompDateIndex: 1,
        },
        {
            name: "WI_1",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 1,
                    open: 1,
                    shut: 0,
                    khMean: 1231.3151895,
                    khMin: 331.081127,
                    khMax: 1672.92916,
                },
                {
                    zoneIndex: 2,
                    open: 1,
                    shut: 0,
                    khMean: 2713.00017425,
                    khMin: 822.713974,
                    khMax: 4422.29676,
                },
                {
                    zoneIndex: 3,
                    open: 1,
                    shut: 0,
                    khMean: 506.8437355,
                    khMin: 130.791149,
                    khMax: 1026.68084,
                },
                {
                    zoneIndex: 4,
                    open: 1,
                    shut: 0,
                    khMean: 781.5949868750001,
                    khMin: 385.392444,
                    khMax: 1506.72756,
                },
                {
                    zoneIndex: 5,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Producer",
                region: "Region 2",
                "user defined category": "my group 2",
            },
            earliestCompDateIndex: 0,
        },
        {
            name: "WI_2",
            completions: [
                {
                    zoneIndex: 0,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
                {
                    zoneIndex: 9,
                    open: 1,
                    shut: 0,
                    khMean: 2.01463155625,
                    khMin: 0.68573069,
                    khMax: 6.83388483,
                },
                {
                    zoneIndex: 10,
                    open: 0,
                    shut: 0,
                    khMean: 0,
                    khMin: 0,
                    khMax: 0,
                },
            ],
            attributes: {
                type: "Producer",
                region: "Region 2",
                "user defined category": "my group 1",
            },
            earliestCompDateIndex: 1,
        },
    ],
    units: {
        kh: {
            unit: "mDm",
            decimalPlaces: 2,
        },
    },
};
