name: Conventional Commits

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    name: Validate pull request title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@00282d63cda40a6eaf3e9d0cbb1ac4384de896e8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}